-- ============================================
-- 技术指标表：日/周/月三张，结构与 stock_daily 对齐
-- ============================================

CREATE TABLE IF NOT EXISTS `stock_indicator_daily` (
    `id`                BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `stock_code`        VARCHAR(16)  NOT NULL                COMMENT '股票代码',
    `trade_date`        DATE         NOT NULL                COMMENT '交易日',
    `ma5`               DECIMAL(12,3) DEFAULT NULL           COMMENT '5日均线',
    `ma10`              DECIMAL(12,3) DEFAULT NULL           COMMENT '10日均线',
    `ma20`              DECIMAL(12,3) DEFAULT NULL           COMMENT '20日均线',
    `ma60`              DECIMAL(12,3) DEFAULT NULL           COMMENT '60日均线',
    `ma120`             DECIMAL(12,3) DEFAULT NULL           COMMENT '120日均线',
    `ma250`             DECIMAL(12,3) DEFAULT NULL           COMMENT '250日均线',
    `boll_upper`        DECIMAL(12,3) DEFAULT NULL           COMMENT 'BOLL上轨',
    `boll_mid`          DECIMAL(12,3) DEFAULT NULL           COMMENT 'BOLL中轨',
    `boll_lower`        DECIMAL(12,3) DEFAULT NULL           COMMENT 'BOLL下轨',
    `macd_dif`          DECIMAL(14,6) DEFAULT NULL           COMMENT 'MACD DIF',
    `macd_dea`          DECIMAL(14,6) DEFAULT NULL           COMMENT 'MACD DEA',
    `macd_hist`         DECIMAL(14,6) DEFAULT NULL           COMMENT 'MACD 柱（DIF-DEA）*2',
    `kdj_k`             DECIMAL(10,4) DEFAULT NULL           COMMENT 'KDJ K值',
    `kdj_d`             DECIMAL(10,4) DEFAULT NULL           COMMENT 'KDJ D值',
    `kdj_j`             DECIMAL(10,4) DEFAULT NULL           COMMENT 'KDJ J值',
    `rsi6`              DECIMAL(10,4) DEFAULT NULL           COMMENT 'RSI-6',
    `rsi12`             DECIMAL(10,4) DEFAULT NULL           COMMENT 'RSI-12',
    `rsi24`             DECIMAL(10,4) DEFAULT NULL           COMMENT 'RSI-24',
    `vol_ma5`           BIGINT       DEFAULT NULL            COMMENT '5日量均线',
    `vol_ma10`          BIGINT       DEFAULT NULL            COMMENT '10日量均线',
    `create_time`       DATETIME     DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_stock_trade_date` (`stock_code`, `trade_date`),
    KEY `idx_trade_date` (`trade_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='股票日频技术指标表';

CREATE TABLE IF NOT EXISTS `stock_indicator_weekly` (
    `id`                BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `stock_code`        VARCHAR(16)  NOT NULL                COMMENT '股票代码',
    `trade_date`        DATE         NOT NULL                COMMENT '该周最后一个交易日',
    `ma5`               DECIMAL(12,3) DEFAULT NULL           COMMENT '5周均线',
    `ma10`              DECIMAL(12,3) DEFAULT NULL           COMMENT '10周均线',
    `ma20`              DECIMAL(12,3) DEFAULT NULL           COMMENT '20周均线',
    `ma60`              DECIMAL(12,3) DEFAULT NULL           COMMENT '60周均线',
    `ma120`             DECIMAL(12,3) DEFAULT NULL           COMMENT '120周均线',
    `ma250`             DECIMAL(12,3) DEFAULT NULL           COMMENT '250周均线',
    `boll_upper`        DECIMAL(12,3) DEFAULT NULL           COMMENT 'BOLL上轨',
    `boll_mid`          DECIMAL(12,3) DEFAULT NULL           COMMENT 'BOLL中轨',
    `boll_lower`        DECIMAL(12,3) DEFAULT NULL           COMMENT 'BOLL下轨',
    `macd_dif`          DECIMAL(14,6) DEFAULT NULL           COMMENT 'MACD DIF',
    `macd_dea`          DECIMAL(14,6) DEFAULT NULL           COMMENT 'MACD DEA',
    `macd_hist`         DECIMAL(14,6) DEFAULT NULL           COMMENT 'MACD 柱',
    `kdj_k`             DECIMAL(10,4) DEFAULT NULL           COMMENT 'KDJ K值',
    `kdj_d`             DECIMAL(10,4) DEFAULT NULL           COMMENT 'KDJ D值',
    `kdj_j`             DECIMAL(10,4) DEFAULT NULL           COMMENT 'KDJ J值',
    `rsi6`              DECIMAL(10,4) DEFAULT NULL           COMMENT 'RSI-6',
    `rsi12`             DECIMAL(10,4) DEFAULT NULL           COMMENT 'RSI-12',
    `rsi24`             DECIMAL(10,4) DEFAULT NULL           COMMENT 'RSI-24',
    `vol_ma5`           BIGINT       DEFAULT NULL            COMMENT '5周量均线',
    `vol_ma10`          BIGINT       DEFAULT NULL            COMMENT '10周量均线',
    `create_time`       DATETIME     DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_stock_trade_date` (`stock_code`, `trade_date`),
    KEY `idx_trade_date` (`trade_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='股票周频技术指标表';

CREATE TABLE IF NOT EXISTS `stock_indicator_monthly` (
    `id`                BIGINT       NOT NULL AUTO_INCREMENT COMMENT '主键ID',
    `stock_code`        VARCHAR(16)  NOT NULL                COMMENT '股票代码',
    `trade_date`        DATE         NOT NULL                COMMENT '该月最后一个交易日',
    `ma5`               DECIMAL(12,3) DEFAULT NULL           COMMENT '5月均线',
    `ma10`              DECIMAL(12,3) DEFAULT NULL           COMMENT '10月均线',
    `ma20`              DECIMAL(12,3) DEFAULT NULL           COMMENT '20月均线',
    `ma60`              DECIMAL(12,3) DEFAULT NULL           COMMENT '60月均线',
    `ma120`             DECIMAL(12,3) DEFAULT NULL           COMMENT '120月均线',
    `ma250`             DECIMAL(12,3) DEFAULT NULL           COMMENT '250月均线',
    `boll_upper`        DECIMAL(12,3) DEFAULT NULL           COMMENT 'BOLL上轨',
    `boll_mid`          DECIMAL(12,3) DEFAULT NULL           COMMENT 'BOLL中轨',
    `boll_lower`        DECIMAL(12,3) DEFAULT NULL           COMMENT 'BOLL下轨',
    `macd_dif`          DECIMAL(14,6) DEFAULT NULL           COMMENT 'MACD DIF',
    `macd_dea`          DECIMAL(14,6) DEFAULT NULL           COMMENT 'MACD DEA',
    `macd_hist`         DECIMAL(14,6) DEFAULT NULL           COMMENT 'MACD 柱',
    `kdj_k`             DECIMAL(10,4) DEFAULT NULL           COMMENT 'KDJ K值',
    `kdj_d`             DECIMAL(10,4) DEFAULT NULL           COMMENT 'KDJ D值',
    `kdj_j`             DECIMAL(10,4) DEFAULT NULL           COMMENT 'KDJ J值',
    `rsi6`              DECIMAL(10,4) DEFAULT NULL           COMMENT 'RSI-6',
    `rsi12`             DECIMAL(10,4) DEFAULT NULL           COMMENT 'RSI-12',
    `rsi24`             DECIMAL(10,4) DEFAULT NULL           COMMENT 'RSI-24',
    `vol_ma5`           BIGINT       DEFAULT NULL            COMMENT '5月量均线',
    `vol_ma10`          BIGINT       DEFAULT NULL            COMMENT '10月量均线',
    `create_time`       DATETIME     DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    PRIMARY KEY (`id`),
    UNIQUE KEY `uk_stock_trade_date` (`stock_code`, `trade_date`),
    KEY `idx_trade_date` (`trade_date`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='股票月频技术指标表';
